# Generated by Django 3.1.3 on 2021-01-17 17:14

import apps.users_profiles.models
import config.extrafields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about', models.TextField()),
                ('cover', config.extrafields.ContentTypeRestrictedFileField(blank=True, upload_to=apps.users_profiles.models.upload_dynamic_cover)),
                ('photo', config.extrafields.ContentTypeRestrictedFileField(blank=True, upload_to=apps.users_profiles.models.upload_dynamic_photo)),
                ('experience', models.JSONField(blank=True, default=dict, null=True)),
                ('education', models.JSONField(blank=True, default=dict, null=True)),
                ('cv', config.extrafields.ContentTypeRestrictedFileField(upload_to=apps.users_profiles.models.upload_dynamic_cv)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
