name: Colset

on:
  push:
      branches:
        - develop

  pull_request:
      branches:
        - develop

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_TEST_PASSWORD }}
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

    - name: Install PostgreSQL 11 client
        run: |
          sudo apt-get -yqq install libpq-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/local.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Django Testing project
      env:
        DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DATABASE_TEST_URL: ${{ secrets.DATABASE_TEST_URL }}

      run: |
        python3 manage.py test

